# Generated by Django 6.0.3 on 2026-03-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CHEMICAL', 'Chemical'), ('GLASSWARE', 'Glassware'), ('COMPONENT', 'Component'), ('INSTRUMENT', 'Lab Instrument'), ('CONSUMABLE', 'Consumable'), ('REAGENT', 'Reagent')], default='CHEMICAL', max_length=20),
        ),
    ]
