# Generated by Django 6.0.3 on 2026-03-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
