# Generated by Django 5.0 on 2026-02-14 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('white_box', 'White Box'), ('gray_box', 'Gray Box'), ('black_box', 'Black Box')], default='white_box', max_length=20, verbose_name='Service')),
                ('status', models.CharField(choices=[('pending', 'Pendiing'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('duration_days', models.IntegerField(default=30)),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='company')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_premium', models.BooleanField(default=False, verbose_name='is_premium')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('EXPIRED', 'expired'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.service')),
            ],
        ),
    ]
