# Generated by Django 6.0.3 on 2026-03-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='purchasedservice',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='PurchasedService',
        ),
    ]
