# Generated by Django 6.0.3 on 2026-03-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glassware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('good', '✅ Good'), ('broken', '❌ Broken'), ('repair', '🔧 In Repair'), ('borrowed', '📤 Borrowed')], default='good', max_length=20)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Here you can add any additional information about the glassware, such as maintenance history, usage instructions, etc.')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glassware', to='inventory.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(help_text='Mandatory unique identifier for each equipment', max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('good', '✅ Good'), ('broken', '❌ Broken'), ('repair', '🔧 In Repair'), ('borrowed', '📤 Borrowed')], default='good', max_length=20)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Here you can add any additional information about the equipment, such as maintenance history, usage instructions, etc.')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='inventory.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Common name of the chemical, e.g., Sulfuric Acid', max_length=200)),
                ('name_iupac', models.CharField(blank=True, max_length=200)),
                ('formula', models.CharField(blank=True, help_text='Ej: H2SO4', max_length=100)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('cas_number', models.CharField(blank=True, help_text='Opcional:CAS number', max_length=50, unique=True)),
                ('pubchem_cid', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('enlace_pubchem', models.URLField(blank=True, help_text='Se llena automáticamente → lleva directo a MSDS y GHS')),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('ml', 'milliliters')], default='g', max_length=10)),
                ('status', models.CharField(choices=[('available', '✅ Available'), ('low', '⚠️ Low Stock'), ('out_of_stock', '❌ Out of Stock'), ('expired', '⏰ Expired')], default='available', max_length=20)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('safety_notes', models.TextField(blank=True, help_text="Observations about the chemical's safety")),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='inventory.laboratory')),
            ],
        ),
        migrations.AddField(
            model_name='laboratory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='inventory.location'),
        ),
    ]
