# Generated by Django 6.0.3 on 2026-03-18 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('responsible', models.CharField(blank=True, max_length=100)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='inventory.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Glassware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('good', '✅ Good'), ('broken', '❌ Broken'), ('repair', '🔧 In Repair'), ('borrowed', '📤 Borrowed')], default='good', max_length=20)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text=' Here you can add any additional information about the glassware, such as maintenance history, usage instructions, etc.')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glasswares', to='inventory.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_name', models.CharField(blank=True, help_text='Model number or name of the equipment', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('good', '✅ Good'), ('broken', '❌ Broken'), ('repair', '🔧 In Repair'), ('borrowed', '📤 Borrowed')], default='good', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='inventory.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('good', '✅ Good'), ('broken', '❌ Broken'), ('missing', '⚠️ Missing')], default='good', max_length=20)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('iupac_name', models.CharField(blank=True, max_length=200)),
                ('formula', models.CharField(blank=True, max_length=100)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('cas_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('pubchem_cid', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('pubchem_link', models.URLField(blank=True)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=10)),
                ('status', models.CharField(choices=[('available', '✅ Available'), ('low', '⚠️ Low Stock'), ('out', '❌ Out of Stock'), ('expired', '⏰ Expired')], default='available', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('safety_notes', models.TextField(blank=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='inventory.laboratory')),
            ],
        ),
    ]
