# Generated by Django 6.0.3 on 2026-03-06 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Campus',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='date_purchased',
            new_name='purchase_date',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='location',
            new_name='campus',
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='supervisor',
            new_name='responsible',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='inventory.laboratory'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='glassware',
            name='notes',
            field=models.TextField(blank=True, help_text=' Here you can add any additional information about the glassware, such as maintenance history, usage instructions, etc.'),
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('iupac_name', models.CharField(blank=True, max_length=200)),
                ('formula', models.CharField(blank=True, max_length=100)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('cas_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('pubchem_cid', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('pubchem_link', models.URLField(blank=True)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=10)),
                ('status', models.CharField(choices=[('available', '✅ Available'), ('low', '⚠️ Low Stock'), ('out', '❌ Out of Stock'), ('expired', '⏰ Expired')], default='available', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('safety_notes', models.TextField(blank=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='inventory.laboratory')),
            ],
        ),
        migrations.DeleteModel(
            name='Chemical',
        ),
    ]
