# Generated by Django 6.0.3 on 2026-04-08 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_otheritem_safematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheritem',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otheritems', to='inventory.laboratory'),
        ),
        migrations.AlterField(
            model_name='safematerial',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safematerials', to='inventory.laboratory'),
        ),
    ]
