# Generated by Django 6.0.3 on 2026-03-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_location_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glassware',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
