# Generated by Django 6.0.3 on 2026-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_otheritem_laboratory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safematerial',
            name='status',
            field=models.CharField(choices=[('available', '✅ Available'), ('low', '⚠️ Low Stock'), ('out', '❌ Out of Stock')], default='available', max_length=20),
        ),
    ]
