# Generated by Django 6.0.3 on 2026-03-06 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_glassware_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glassware',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glasswares', to='inventory.laboratory'),
        ),
    ]
