# Generated by Django 6.0.3 on 2026-04-27 11:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_safematerial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='The model or name of the process trainer should be started with VSEN', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processtrainers', to='inventory.laboratory')),
            ],
            options={
                'verbose_name': 'Process Trainer',
                'verbose_name_plural': 'Process Trainers',
                'ordering': ['date_added'],
            },
        ),
    ]
