# Generated by Django 6.0.3 on 2026-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.CharField(choices=[('good', '✅ Good'), ('broken', '❌ Broken'), ('missing', '⚠️ Missing')], default='good', max_length=20),
        ),
    ]
