# Generated by Django 6.0.3 on 2026-03-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labsession',
            name='color',
        ),
    ]
