# Generated by Django 6.0.3 on 2026-03-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labsession',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to='inventory.laboratory'),
        ),
        migrations.AlterField(
            model_name='labsession',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_sessions', to='schedule.scheduleperiod'),
        ),
    ]
