# Generated by Django 6.0.3 on 2026-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_labsession_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsession',
            name='practice_complete',
            field=models.BooleanField(default=False),
        ),
    ]
