# Generated by Django 5.1.6 on 2025-02-16 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLR', '0002_register_user_delete_login_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
