# Generated by Django 5.1.6 on 2025-02-16 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLR', '0003_register_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='register_user',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
