# Generated by Django 5.1.6 on 2025-02-16 01:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLR', '0004_remove_register_user_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='confirm_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
