# Generated by Django 5.1.6 on 2025-02-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LLR', '0005_register_user_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='confirm_password',
        ),
    ]
