# Generated by Django 5.1.6 on 2025-02-17 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
                ('range', models.CharField(max_length=50)),
                ('cant', models.IntegerField()),
                ('Obsevation', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
