# Generated by Django 5.1.6 on 2025-02-18 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0002_rename_aparatus_aparatu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vol', models.IntegerField()),
                ('recipe', models.ImageField(upload_to='')),
                ('location', models.CharField(max_length=50)),
                ('Obsevation', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='glaswerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vol', models.IntegerField()),
                ('recipe', models.ImageField(upload_to='')),
                ('Observation', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
