# Generated by Django 5.1.6 on 2025-02-18 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0003_chemsub_glaswerk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vol', models.IntegerField()),
                ('recipe', models.IntegerField()),
                ('Observation', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='safety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
                ('range', models.IntegerField()),
                ('recipe', models.IntegerField()),
                ('Observation', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='chemsub',
            name='recipe',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='glaswerk',
            name='recipe',
            field=models.IntegerField(),
        ),
    ]
