# Generated by Django 5.1.6 on 2025-02-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0004_other_safety_alter_chemsub_recipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparatu',
            old_name='Obsevation',
            new_name='Observation',
        ),
        migrations.RenameField(
            model_name='chemsub',
            old_name='Obsevation',
            new_name='Observation',
        ),
    ]
