# Generated by Django 5.1.6 on 2025-02-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0005_rename_obsevation_aparatu_observation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemsub',
            old_name='recipe',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='glaswerk',
            old_name='recipe',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='other',
            old_name='recipe',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='safety',
            old_name='recipe',
            new_name='container',
        ),
    ]
