# Generated by Django 5.2 on 2025-04-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0006_rename_recipe_chemsub_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparatu',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chemsub',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
