# Generated by Django 5.2 on 2025-04-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0007_alter_aparatu_name_alter_chemsub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemsub',
            name='container',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='chemsub',
            name='vol',
            field=models.CharField(),
        ),
    ]
