# Generated by Django 5.2 on 2025-04-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0008_alter_chemsub_container_alter_chemsub_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaswerk',
            name='container',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='glaswerk',
            name='vol',
            field=models.CharField(max_length=10),
        ),
    ]
