# Generated by Django 5.2 on 2025-04-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0009_alter_glaswerk_container_alter_glaswerk_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaswerk',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
