# Generated by Django 5.2 on 2025-04-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0010_alter_glaswerk_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaswerk',
            name='container',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='glaswerk',
            name='vol',
            field=models.CharField(max_length=50),
        ),
    ]
