# Generated by Django 5.2 on 2025-04-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0011_alter_glaswerk_container_alter_glaswerk_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='container',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='other',
            name='vol',
            field=models.CharField(),
        ),
    ]
