# Generated by Django 5.2 on 2025-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0012_alter_other_container_alter_other_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='container',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='other',
            name='vol',
            field=models.CharField(max_length=50),
        ),
    ]
