# Generated by Django 5.2 on 2025-04-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPanel', '0013_alter_other_container_alter_other_vol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='other',
            old_name='vol',
            new_name='mark',
        ),
    ]
