# Generated by Django 6.0.3 on 2026-03-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del material')),
                ('description', models.TextField(verbose_name='Descripción del uso')),
                ('youtube_id', models.CharField(max_length=20, verbose_name='ID de YouTube (ej: dQw4w9wg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video Material',
                'verbose_name_plural': 'Video Materials',
            },
        ),
    ]
