# Generated by Django 6.0.3 on 2026-03-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the video material')),
                ('description', models.TextField(verbose_name='Description of the usage')),
                ('iframe', models.TextField(max_length=1000, verbose_name='Iframe code for the video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video Material',
                'verbose_name_plural': 'Video Materials',
            },
        ),
    ]
