# Generated by Django 6.0.3 on 2026-03-11 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomaterial',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='videomaterial',
            name='iframe',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000, verbose_name='Iframe code for the video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videomaterial',
            name='description',
            field=models.TextField(verbose_name='Description of the usage'),
        ),
        migrations.AlterField(
            model_name='videomaterial',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name of the video material'),
        ),
    ]
